version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: duosync
    env_file:
      - .env
    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - redis
    networks:
      - duosync-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: DuoSync
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - duosync-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - duosync-network

volumes:
  mysql-data: { }

networks:
  duosync-network:
    driver: bridge