version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: duosync
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: DuoSync
      SPRING_DATASOURCE_URL: ${MYSQL_SOURCE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: DuoSync
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data: { }