ssh -o StrictHostKeyChecking=no ubuntu@*** << 'EOF'
  cd ~/app/DuoSync
  git pull origin dev
  
  # .env 파일 생성 (필요한 환경 변수 설정)
  echo "MYSQL_SOURCE==***" > .env
  echo "MYSQL_USER=***" >> .env
  echo "MYSQL_PASSWORD=***" >> .env
  echo "REDIS_HOST=***" >> .env
  echo "JWT_SECRET_KEY=***" >> .env
  echo "OAUTH_NAVER_CLIENT_ID=***" >> .env
  echo "OAUTH_NAVER_CLIENT_SECRET=***" >> .env
  echo "OAUTH_NAVER_REDIRECT_URI=***" >> .env
  echo "OAUTH_GOOGLE_CLIENT_ID=***" >> .env
  echo "OAUTH_GOOGLE_CLIENT_SECRET=***" >> .env
  echo "OAUTH_GOOGLE_REDIRECT_URI=***" >> .env
  
  # Docker Compose로 애플리케이션 시작
  docker-compose up --build -d
EOF
